source "http://rubygems.org"

# Declare your gem's dependencies in simple_auth.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

group :development do
	gem 'sqlite3', '1.3.5'
	gem 'rspec-rails', '2.10.0'
	gem 'guard-rspec', '0.5.5'
	gem 'annotate', '~> 2.4.1.beta'
end

group :test do
	gem 'capybara', '1.1.2'
	gem 'factory_girl_rails', '1.4.0'
end

# jquery-rails is used by the dummy application
gem "jquery-rails"
gem 'faker', '1.0.1'

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use debugger
# gem 'debugger'
